version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      MYSQL_TCP_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DBNAME}
    env_file:
      - .env

  nestjs:
    container_name: nestjs_api_dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mysql
    expose:
      - '${API_PORT}'
    env_file:
      - .env